language: python
python:
    - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

env:
    - PLATFORMIO_CI_SRC=examples/GY-21_test/GY-21_test.ino

install:
    - pip install -U platformio
    - pio update

script:
    - pio ci --lib="." --board=uno --board=nodemcuv2
