language: python

python:

    - "2.7"



install:

    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"



script:

    - platformio ci examples/HTU21_test --board=uno --board=due --board=teensy31 --board=esp01